version: "3.3"

services:
  auth:
    image: quay.io/keycloak/keycloak:19.0.2
    command: start-dev
    env_file:
      - keycloak.env
    ports:
      - "8090:8080"

  adapter:
    build: ./keycloak-adapter/
    env_file:
      - adapter.env
    ports:
      - "3000:3000"
    volumes:
      - "~/container_volumes/nginx/:/var/log/nginx"
